[package]
name = "gale"
version = "0.6.2"
description = "A lightweight mod manager for Thunderstore"
authors = ["Kesomannen"]
license = "GPL-3.0"
repository = "https://github.com/Kesomannen/gale"
default-run = "gale"
edition = "2021"
rust-version = "1.79"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6.7", features = [ "cli", "fs-read-file", "app-all", "updater", "clipboard-all", "shell-open", "http-request", "window-all", "dialog-all", "clipboard" ] }
tokio = { version = "1", features = ["full"] }

anyhow = "1.0"
thiserror = "1.0"
justerror = "1.0"

indexmap = { version = "2.2", features = ["serde"] }
open = "5.1"
itertools = "0.13"
zip = "0.6"
futures-util = { version = "0.3", features = ["io"] }
uuid = { version = "1.7", features = ["serde"] }
reqwest =  { version = "0.12", features = ["json", "stream"] }
walkdir = "2"
typeshare = "1.0"
image = "0.25"
semver = "1.0"
serde_yaml = "0.9"
base64 = "0.22"
lazy_static = "1.4"
heck = "0.5"
log = "0.4"
simplelog = "0.12"
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-deep-link = "=0.1.2"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
keyring = "3.0.3"
dirs-next = "2.0.0"

[target.'cfg(target_os="macos")'.dependencies]
objc = "0.2"

[target.'cfg(target_os="linux")'.dependencies]
webkit2gtk = "0.18"

[features]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
strip = true # Remove debug symbols
