[package]
name = "gale"
version = "0.2.0"
description = "A lightweight mod manager for Thunderstore"
authors = ["Kesomannen"]
license = "GPL-3.0"
repository = ""
default-run = "gale"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6.1", features = [ "updater", "clipboard-all", "shell-open", "http-request", "window-all", "dialog-all", "clipboard" ] }
tokio = { version = "1", features = ["full"] }

anyhow = "1.0"
thiserror = "1.0"
justerror = "1.0"

indexmap = "2.2"
open = "5.1"
itertools = "0.12"
zip = "0.6"
zip-extract = "0.1"
futures-util = { version = "0.3", features = ["io"] }
uuid = { version = "1.7", features = ["serde"] }
reqwest =  { version = "0.12", features = ["json", "stream"] }
walkdir = "2"
typeshare = "1.0"
tauri-plugin-deep-link = "=0.1.2"
image = "0.25"
semver = "1.0"
serde_yaml = "0.9"
base64 = "0.22"
lazy_static = "1.4"
heck = "0.5"
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
