[package]
name = "gale"
version = "0.7.0"
description = "A lightweight mod manager for Thunderstore"
authors = ["Kesomannen"]
license = "GPL-3.0"
repository = "https://github.com/Kesomannen/gale"
default-run = "gale"
edition = "2021"
rust-version = "1.79"

[lib]
name = "gale_lib"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "gale"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta", features = ["unstable"] }
tokio = { version = "1", features = ["full"] }

anyhow = "1.0"
thiserror = "1.0"
justerror = "1.0"

indexmap = { version = "2.2", features = ["serde"] }
open = "5.1"
itertools = "0.13"
zip = "0.6"
futures-util = { version = "0.3", features = ["io"] }
uuid = { version = "1.7", features = ["serde"] }
reqwest =  { version = "0.12", features = ["json", "stream"] }
walkdir = "2"
typeshare = "1.0"
image = "0.25"
semver = { version = "1.0", features = ["serde"] }
serde_yaml = "0.9"
base64 = "0.22"
lazy_static = "1.4"
heck = "0.5"
log = "0.4"
simplelog = "0.12"
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-deep-link = "2.0.0-beta.9"
tauri-plugin-window-state = "2.0.0-beta.11"
tauri-plugin-dialog = "2.0.0-beta.11"
tauri-plugin-shell = "2.0.0-beta.9"
tauri-plugin-os = "2.0.0-beta.8"
tauri-plugin-process = "2.0.0-beta.8"
tauri-plugin-updater = "2.0.0-beta.10"
tauri-plugin-clipboard-manager = "2.1.0-beta.6"
tauri-plugin-http = "2.0.0-beta.12"
keyring = "3.0.3"
dirs-next = "2.0.0"

[target.'cfg(target_os="macos")'.dependencies]
objc = "0.2"

[target.'cfg(target_os="linux")'.dependencies]
webkit2gtk = "2.0.1"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-cli = "2.0.0-beta.8"

[features]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
strip = true # Remove debug symbols
