[general]
repository = "https://thunderstore.io"

[package]
name = "GaleModManager"
namespace = "Kesomannen"
description = "A modern and lightweight mod manager for many games on Thunderstore. INSTALL FROM THUNDERSTORE.IO!"
websiteUrl = "https://github.com/Kesomannen/gale"

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "app-icon@0,25x.png"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE.md"
target = "LICENSE.md"

[[build.copy]]
source = "src-tauri\\target\\release\\bundle\\nsis"
target = ""

[publish]
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["tools"]
